package md;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfStamper;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;


/**
 * How to Add Text To Existing PDF in java
 * Example Using iText library - core java tutorial
 */
public class AddTextToExistingPDF2 {

    public static void main(String[] args) throws Exception {


        String inputFilePath = "C:/Users/abid_/Desktop/ABNformEnglish.pdf"; // Existing file
        String outputFilePath = "C:/Users/abid_/Desktop/ABNformEnglish___.pdf"; // New file
        OutputStream fos = new FileOutputStream(new File(outputFilePath));


        PdfReader pdfReader = new PdfReader(inputFilePath);
        int pages = pdfReader.getNumberOfPages();
        System.out.println("No of Pages: -- " + pages);
        PdfStamper pdfStamper = new PdfStamper(pdfReader, fos);


        // loop on all the PDF pages
        // i is the pdfPageNumber
        for (int i = 1; i <= pdfReader.getNumberOfPages(); i++) {

            if (i == 1) {
                PdfContentByte pdfContentByte = pdfStamper.getOverContent(i);

                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(520, 760);
                pdfContentByte.showText("MRN: " + "310025");
                pdfContentByte.endText();

                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(410.0f, 80.0f);
                pdfContentByte.showText("02/09/2021");
                pdfContentByte.endText();


            }
            /*if (i == 2) {
                PdfContentByte pdfContentByte = pdfStamper.getOverContent(i);

                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont(BaseFont.TIMES_BOLD, "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(45, 750.0f);
                pdfContentByte.showText("MRN:  310056");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 775);
                pdfContentByte.showText("LastName" + " , " + "FirstName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 765);
                pdfContentByte.showText("ClientName " + "        Sex:" + "gender");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 755);
                pdfContentByte.showText("DOB: " + "DOB " + "        Age:" + ":Age");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 745);
                pdfContentByte.showText("MRN: " + "MRN " + "        DOS: " + "DOS");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 735);
                pdfContentByte.showText("Dr. " + "DoctorName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(40, 645);
                pdfContentByte.showText("Prefix MR.");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(120.0f, 645);
                pdfContentByte.showText("FirstName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(280.0f, 645);
                pdfContentByte.showText("LastName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(450.0f, 645);
                pdfContentByte.showText("MaritalStatus");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(50, 605);
                pdfContentByte.showText("DOB");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(180.0f, 605);
                pdfContentByte.showText("gender");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(280.0f, 605);
                pdfContentByte.showText("PhNumber");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(450.0f, 605);
                pdfContentByte.showText("SSN");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(40, 560);
                pdfContentByte.showText("Address");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(280.0f, 560);
                pdfContentByte.showText("City");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(430.0f, 560);
                pdfContentByte.showText("State");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(490.0f, 560);
                pdfContentByte.showText("ZipCode");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(50, 515);
                pdfContentByte.showText("Email");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(400.0f, 535);
                pdfContentByte.showText("HearAboutUsString");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(270.0f, 525);
                pdfContentByte.showText("HearAboutUsString2");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(270.0f, 515);
                pdfContentByte.showText("HearAboutUsString3");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(50, 475);
                pdfContentByte.showText("Employer");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(360.0f, 475);
                pdfContentByte.showText("EmployerPhone");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(50, 430);
                pdfContentByte.showText("PriCarePhy");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(360.0f, 430);
                pdfContentByte.showText("Primary Care Phy Number");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(80.0f, 370);
                pdfContentByte.showText("GuarantorFirstName");//Responsible Patrty FisgtName
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(320.0f, 370);
                pdfContentByte.showText("GuarantorLastName");//Responsible Patrty LastName
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(450.0f, 370);
                pdfContentByte.showText("GuarantorDOB");//Responsible Party DOB
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(40, 325);
                pdfContentByte.showText("RelationShip To Pat");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(280, 325);
                pdfContentByte.showText("Repos CITY");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(430, 325);
                pdfContentByte.showText("STATE");//Repos Party State
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(490, 325);
                pdfContentByte.showText("Repos Zipcode");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(50, 285);
                pdfContentByte.showText("Repos Address");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(280, 285);
                pdfContentByte.showText("Repos PhNumber");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(80.0f, 220);
                pdfContentByte.showText("NextofKinName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(320.0f, 220);
                pdfContentByte.showText("RelationToPatientER");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(490.0f, 220);
                pdfContentByte.showText("PhoneNumberER");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(460, 175);
                pdfContentByte.showText("RelationToPatientER");//authorized acced to patient Room
                pdfContentByte.endText();
            }
            if (i == 3) {
                PdfContentByte pdfContentByte = pdfStamper.getOverContent(i);

                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont(BaseFont.TIMES_BOLD, "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(45, 750.0f);
                pdfContentByte.showText("MRN:  310056");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 775);
                pdfContentByte.showText("LastName" + " , " + "FirstName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 765);
                pdfContentByte.showText("ClientName " + "        Sex:" + "gender");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 755);
                pdfContentByte.showText("DOB: " + "DOB " + "        Age:" + ":Age");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 745);
                pdfContentByte.showText("MRN: " + "MRN " + "        DOS: " + "DOS");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 735);
                pdfContentByte.showText("Dr. " + "DoctorName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(170.0f, 605);
                pdfContentByte.showText("WorkersCompPolicyString");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(150, 590);
                pdfContentByte.showText("MotorVehAccidentString");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(80.0f, 545);
                pdfContentByte.showText("PriInsuranceName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(40, 505);
                pdfContentByte.showText("Subscriber FirstName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(180, 505);
                pdfContentByte.showText("Subscriber LastName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(385, 505);
                pdfContentByte.showText("PrimarySSN");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(500, 505);
                pdfContentByte.showText("PrimaryDOB");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(60, 460);
                pdfContentByte.showText("Subs CellPh");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(225, 460);
                pdfContentByte.showText("MemId");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(420.0f, 460);
                pdfContentByte.showText("GrpNumber");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(80.0f, 420);
                pdfContentByte.showText("PatientRelationtoPrimary");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(50, 360);
                pdfContentByte.showText("Date of accident");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(180, 360);
                pdfContentByte.showText("AccT Auto/work");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(310, 360);
                pdfContentByte.showText("Driver/passenger/pedestrian/cyclist");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(60, 315);
                pdfContentByte.showText("Name of Insurance Company");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(385, 315);
                pdfContentByte.showText("InsCompany PHNo");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(40, 275);
                pdfContentByte.showText("Company Address");//Company
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(225, 275);
                pdfContentByte.showText("City");//Company
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(320, 275);
                pdfContentByte.showText("State");//Company
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(385, 275);
                pdfContentByte.showText(" ZipCode");//Company
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(460, 275);
                pdfContentByte.showText(" Faxno");//Company
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(60, 230);
                pdfContentByte.showText(" Name of insured");//Company
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(320, 230);
                pdfContentByte.showText(" Adjuster Name: ");//Company
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(60, 185);
                pdfContentByte.showText(" Policy NUmber: ");//Company
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(300, 185);
                pdfContentByte.showText("Reported Y/N ");//Company
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(385, 185);
                pdfContentByte.showText("ClaimNumbe");//Company
                pdfContentByte.endText();
            }
            if (i == 4) {
                final PdfContentByte pdfContentByte = pdfStamper.getOverContent(i);
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont(BaseFont.TIMES_BOLD, "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(45, 750.0f);
                pdfContentByte.showText("MRN:  310056");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 775);
                pdfContentByte.showText("LastName" + " , " + "FirstName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 765);
                pdfContentByte.showText("ClientName " + "        Sex:" + "gender");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 755);
                pdfContentByte.showText("DOB: " + "DOB " + "        Age:" + ":Age");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 745);
                pdfContentByte.showText("MRN: " + "MRN " + "        DOS: " + "DOS");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 735);
                pdfContentByte.showText("Dr. " + "DoctorName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(100.0f, 500);
                pdfContentByte.showText("SecInsuranceName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(100.0f, 450);
                pdfContentByte.showText("SubscriberName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(340.0f, 450);
                pdfContentByte.showText("SubscriberDOB");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(100.0f, 400);
                pdfContentByte.showText("MemberID_2");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(340.0f, 400);
                pdfContentByte.showText("GroupNumber_2");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(280.0f, 200);
                pdfContentByte.showText("LastName "+ ", " + "FirstName "+ " " + "MiddleInitial");
                pdfContentByte.endText();
            }
            if (i == 5) {
                final PdfContentByte pdfContentByte = pdfStamper.getOverContent(i);
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont(BaseFont.TIMES_BOLD, "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(45, 750.0f);
                pdfContentByte.showText("MRN:  310056");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 775);
                pdfContentByte.showText("LastName" + " , " + "FirstName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 765);
                pdfContentByte.showText("ClientName " + "        Sex:" + "gender");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 755);
                pdfContentByte.showText("DOB: " + "DOB " + "        Age:" + ":Age");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 745);
                pdfContentByte.showText("MRN: " + "MRN " + "        DOS: " + "DOS");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 735);
                pdfContentByte.showText("Dr. " + "DoctorName");
                pdfContentByte.endText();

            }
            if (i == 6) {
                final PdfContentByte pdfContentByte = pdfStamper.getOverContent(i);
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont(BaseFont.TIMES_BOLD, "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(45, 750.0f);
                pdfContentByte.showText("MRN:  310056");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 775);
                pdfContentByte.showText("LastName" + " , " + "FirstName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 765);
                pdfContentByte.showText("ClientName " + "        Sex:" + "gender");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 755);
                pdfContentByte.showText("DOB: " + "DOB " + "        Age:" + ":Age");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 745);
                pdfContentByte.showText("MRN: " + "MRN " + "        DOS: " + "DOS");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 735);
                pdfContentByte.showText("Dr. " + "DoctorName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(70, 95);
                pdfContentByte.showText("FirstName");
                pdfContentByte.endText();
            }
            if (i == 7) {
                final PdfContentByte pdfContentByte = pdfStamper.getOverContent(i);
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont(BaseFont.TIMES_BOLD, "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(45, 750.0f);
                pdfContentByte.showText("MRN:  310056");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 775);
                pdfContentByte.showText("LastName" + " , " + "FirstName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 765);
                pdfContentByte.showText("ClientName " + "        Sex:" + "gender");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 755);
                pdfContentByte.showText("DOB: " + "DOB " + "        Age:" + ":Age");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 745);
                pdfContentByte.showText("MRN: " + "MRN " + "        DOS: " + "DOS");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 735);
                pdfContentByte.showText("Dr. " + "DoctorName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(70, 260);
                pdfContentByte.showText("PR sign");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(430.0f, 260);
                pdfContentByte.showText("Date");
                pdfContentByte.endText();
            }
            if (i == 8) {
                final PdfContentByte pdfContentByte = pdfStamper.getOverContent(i);
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont(BaseFont.TIMES_BOLD, "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(45, 750.0f);
                pdfContentByte.showText("MRN:  310056");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 775);
                pdfContentByte.showText("LastName" + " , " + "FirstName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 765);
                pdfContentByte.showText("ClientName " + "        Sex:" + "gender");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 755);
                pdfContentByte.showText("DOB: " + "DOB " + "        Age:" + ":Age");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 745);
                pdfContentByte.showText("MRN: " + "MRN " + "        DOS: " + "DOS");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 735);
                pdfContentByte.showText("Dr. " + "DoctorName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(100.0f, 585);
                pdfContentByte.showText("LastName "+ ", " + "FirstName "+ " " + "MiddleInitial");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(380.0f, 585);
                pdfContentByte.showText("DOB");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(50.0f, 540);
                pdfContentByte.showText("PriInsuranceName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(380.0f, 540);
                pdfContentByte.showText("MemId");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(100.0f, 485);
                pdfContentByte.showText("DOS");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(380.0f, 485);
                pdfContentByte.showText("PatientRelationtoPrimary");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(50, 340);
                pdfContentByte.showText("LastName "+ ", " + "FirstName "+ " " + "MiddleInitial");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(60, 150);
                pdfContentByte.showText("PatientSign");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(430.0f, 150);
                pdfContentByte.showText("Date");
                pdfContentByte.endText();
            }
            if (i == 9) {
                final PdfContentByte pdfContentByte = pdfStamper.getOverContent(i);
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont(BaseFont.TIMES_BOLD, "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(45, 750.0f);
                pdfContentByte.showText("MRN:  310056");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 775);
                pdfContentByte.showText("LastName" + " , " + "FirstName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 765);
                pdfContentByte.showText("ClientName " + "        Sex:" + "gender");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 755);
                pdfContentByte.showText("DOB: " + "DOB " + "        Age:" + ":Age");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 745);
                pdfContentByte.showText("MRN: " + "MRN " + "        DOS: " + "DOS");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 735);
                pdfContentByte.showText("Dr. " + "DoctorName");
                pdfContentByte.endText();
            }
            if (i == 10) {
                final PdfContentByte pdfContentByte = pdfStamper.getOverContent(i);
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont(BaseFont.TIMES_BOLD, "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(45, 750.0f);
                pdfContentByte.showText("MRN:  310056");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 775);
                pdfContentByte.showText("LastName" + " , " + "FirstName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 765);
                pdfContentByte.showText("ClientName " + "        Sex:" + "gender");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 755);
                pdfContentByte.showText("DOB: " + "DOB " + "        Age:" + ":Age");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 745);
                pdfContentByte.showText("MRN: " + "MRN " + "        DOS: " + "DOS");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 735);
                pdfContentByte.showText("Dr. " + "DoctorName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(70, 200);
                pdfContentByte.showText("PatSign");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(430.0f, 200);
                pdfContentByte.showText("Date");
                pdfContentByte.endText();
            }
            if (i == 11) {
                final PdfContentByte pdfContentByte = pdfStamper.getOverContent(i);
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont(BaseFont.TIMES_BOLD, "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(45, 750.0f);
                pdfContentByte.showText("MRN:  310056");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 775);
                pdfContentByte.showText("LastName" + " , " + "FirstName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 765);
                pdfContentByte.showText("ClientName " + "        Sex:" + "gender");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 755);
                pdfContentByte.showText("DOB: " + "DOB " + "        Age:" + ":Age");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 745);
                pdfContentByte.showText("MRN: " + "MRN " + "        DOS: " + "DOS");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 8.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(470, 735);
                pdfContentByte.showText("Dr. " + "DoctorName");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(70, 215);
                pdfContentByte.showText("PT SIgn");
                pdfContentByte.endText();
                pdfContentByte.beginText();
                pdfContentByte.setFontAndSize(BaseFont.createFont("Times-Roman", "Cp1257", true), 10.0f);
                pdfContentByte.setColorFill(BaseColor.BLACK);
                pdfContentByte.setTextMatrix(430.0f, 215);
                pdfContentByte.showText("Date");
                pdfContentByte.endText();
            }*/

        }

        pdfStamper.close(); //close pdfStamper

        System.out.println("Modified PDF created in >> " + outputFilePath);

    }

}